### ISSUE TITLE
"All A/B Tests" listing is empty even though they exists

### ISSUE THREAD

**Issue by Cestis** [Gaya/ab-testing-for-wp#33] opened 2019-11-22 11:05 UTC
![image](https://user-images.githubusercontent.com/3482915/69420818-c47e9a00-0d1f-11ea-9817-892fe90d0a86.png)

The list is always empty, even after adding, saving and publishing the test. It is still accessible through URL. Also not visible on any other listing (pages, posts, comments, etc.).

Not sure if it is connected, but then on a page, I get this error in the console:
![image](https://user-images.githubusercontent.com/3482915/69421291-f5130380-0d20-11ea-80a1-8ac7893bc69b.png)

**Comment by Gaya** [comment] 2019-11-22 14:40
@Cestis thanks for reporting. I'll get on it ASAP.

**Comment by Gaya** [comment] 2020-02-03 14:56
Closing this issues as I cannot reproduce

**Closed by Gaya** 2020-02-03 14:56 UTC
Labels: bug, can't reproduce
